

/**
 * Public constants.
 */
export class Constants {
  /**
   * Full percent.
   */
  static readonly FULL_PERCENT: string = '100%';

  /**
   * Byte Unit.
   */
  static readonly BYTE_UNIT: string = ' Byte';

  /**
   * File Path Name.
   */
  static readonly FILE_PATH_NAME: string = '/test.txt';

  /**
   * Write Content.
   */
  static readonly WRITE_CONTENT: string = '/test.txt';

  /**
   * Apply the spatial statistics page.
   */
  static readonly APP_SPACE_PAGE: string = 'AppSpacePage';

  /**
   * File System Storage Statistics page.
   */
  static readonly FILE_SPACE_PAGE: string = 'FileSpacePage';
}